# Generated by Django 4.1.6 on 2023-02-11 08:13

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeAre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Основная ссылка')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='where_we_are/', verbose_name='Основная фотография')),
            ],
            options={
                'verbose_name': 'Где мы есть ?',
                'verbose_name_plural': 'Где мы есть ?',
            },
        ),
    ]
