# Generated by Django 4.1.5 on 2023-03-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_setting_description_en_setting_description_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на iframe instagram'),
        ),
    ]
