# Generated by Django 4.1.5 on 2023-02-06 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Reservation',
        ),
    ]
