# Generated by Django 4.1.5 on 2023-03-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_about_alter_weare_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='id_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID чата для контактов'),
        ),
        migrations.AddField(
            model_name='setting',
            name='id_reservation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID чата для бронь'),
        ),
        migrations.AddField(
            model_name='setting',
            name='id_review',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID чата для отзывов'),
        ),
    ]
