# Generated by Django 4.1.6 on 2023-02-12 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_weare'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
