# Generated by Django 4.1.6 on 2023-02-12 16:02

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Основная ссылка')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='parners/', verbose_name='Основная фотография')),
            ],
            options={
                'verbose_name': 'Наш партер',
                'verbose_name_plural': 'Наши партеры',
            },
        ),
    ]
