# Generated by Django 4.1.5 on 2023-02-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Проверка'),
        ),
    ]
