# Generated by Django 4.1.5 on 2023-02-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_setting_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='address_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на адрес'),
        ),
    ]
