# Generated by Django 4.1.5 on 2023-02-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0016_alter_setting_address_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='backround_image',
            field=models.ImageField(null=True, upload_to='backround_image/', verbose_name='Изображение на заднем плане в главной странице'),
        ),
    ]
