# Generated by Django 4.1.5 on 2023-02-10 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0017_setting_backround_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='room',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
