# Generated by Django 4.1.5 on 2023-02-21 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_telegramuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
