# Generated by Django 4.1.5 on 2023-03-14 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='room',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='room',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='room',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='room',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='room',
            name='title_ru',
        ),
    ]
