# Generated by Django 4.1.5 on 2023-02-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Проверка'),
        ),
    ]
