# Generated by Django 4.1.5 on 2023-03-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_room_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание комнаты'),
        ),
        migrations.AddField(
            model_name='room',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание комнаты'),
        ),
        migrations.AddField(
            model_name='room',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание комнаты'),
        ),
        migrations.AddField(
            model_name='room',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название комнаты'),
        ),
        migrations.AddField(
            model_name='room',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название комнаты'),
        ),
        migrations.AddField(
            model_name='room',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название комнаты'),
        ),
    ]
