# Generated by Django 4.1.5 on 2023-02-16 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_reservation_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='beds',
        ),
        migrations.RemoveField(
            model_name='room',
            name='sleeps',
        ),
    ]
